# Generated by Django 6.0.5 on 2026-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='response_message',
            new_name='tailored_resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
