# Generated by Django 6.0 on 2026-01-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
