# Generated by Django 6.0 on 2026-01-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='extracted_text',
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
    ]
