# Generated by Django 6.0 on 2026-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_extracted_text_resume_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
