# Generated by Django 6.0 on 2026-01-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_extracted_text_alter_resume_parsed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
    ]
