# Generated by Django 6.0.5 on 2026-05-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
