# Generated by Django 6.0.5 on 2026-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_ai_analysis_resume_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
