# Generated by Django 6.0.5 on 2026-05-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resume_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tailored_resume',
            field=models.TextField(blank=True),
        ),
    ]
