# Generated by Django 6.0.5 on 2026-05-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_resume_tailored_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tailored_resume',
        ),
    ]
